### ISSUE TITLE
Pre-processing for HAST-IDS 

### ISSUE THREAD

**Issue by deepakkochhar11** [echowei/DeepTraffic#1]
Sir
Can you provide the **preprocessing tool and code** to split the raw pcap into flows just as you did for the malware and encrypted traffic classification.

**Comment by echowei** [comment]
Thanks for your advice. I will add these files another day, please  be patient.

**Comment by SpykerX** [comment]
Hi  Echowei !
     When I running your code,  I faced with problem on stage  training  a new model and save it, 
namely  in this line: train_accuracy = accuracy.eval(session=sess, feed_dict={x: batch[0], y_: batch[1], keep_prob: 1.0}) . I have arise : ValueError: Cannot feed value of shape (50, 10) for Tensor 'Placeholder_1:0', which has shape '(?, 6)'. 
    Please can you help me or give some hint how solve this error.

**Comment by echowei** [comment]
Please note #19: Note: if class numer is 2 or 20, please edit the variable named "num_classes" in /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py". TF has been updated several versions, and I'm not sure if it's still available

**Comment by SpykerX** [comment]
Thank you for the answer!

вс, 28 июл. 2019 г., 08:21 wangwei <notifications@github.com>:
