### ISSUE TITLE
作者您好，您的项目DeepTraffic有没有比较快的下载方法？

### ISSUE THREAD

**Issue by smithCoderLeo** [echowei/DeepTraffic#10]
目前我使用了git cmd直接下载，但速度大概只有几十kB每秒，并且没有下载成功过，是否需要科学上网，还请指点！

**Comment by wmn7** [comment]
你好, 我已经下载好了, 要不我直接邮件发送给你.

**Comment by smithCoderLeo** [comment]
> 你好, 我已经下载好了, 要不我直接邮件发送给你.

你好，非常感谢你的帮助！想问下可以QQ发给我吗？我QQ是540089973，非常感谢！！

**Comment by oceanzm1992** [comment]
> 你好, 我已经下载好了, 要不我直接邮件发送给你.

您好，我一直下载失败，方便的话，请您发给我一份，不胜感激。邮箱是：928033434@qq.com

**Comment by wcy-source** [comment]
你好，能发我一份吗？我的邮箱是：2541982163@qq.com

**Comment by ixiaozhuai** [comment]
> 你好，能发我一份吗？我的邮箱是：[2541982163@qq.com](mailto:2541982163@qq.com)

你好，可以请教一下该程序的相关问题嘛

**Comment by ixiaozhuai** [comment]
> > 你好, 我已经下载好了, 要不我直接邮件发送给你.
> 
> 您好，我一直下载失败，方便的话，请您发给我一份，不胜感激。邮箱是：[928033434@qq.com](mailto:928033434@qq.com)

你好，可以请教一下该程序的相关问题嘛

**Comment by ixiaozhuai** [comment]
> 你好, 我已经下载好了, 要不我直接邮件发送给你.

你好，可以请教一下该程序的相关问题嘛
