### ISSUE TITLE
关于MAC address and IP address的处理

### ISSUE THREAD

**Issue by wmn7** [echowei/DeepTraffic#11]
你好, 在你的论文"Malware Traffic Classification Using Convolutional Neural Network for Representation Learning"中提到, 在处理数据的时候, 需要randomizes MAC address and IP address in in data link layer.

但是, 我在看你仓库代码的时候(这个文件夹, 2.encrypted_traffic_classification/2.PreprocessedTools), 没有看到相应的对IP和MAC的处理内容. 想问一下你是在哪里对这两个进行处理的呢.

期待你的回复, 祝好.

**Comment by ruibao123** [comment]
我跟你有相同的疑惑。。。

**Comment by echowei** [comment]
已回复您的邮件，请查收。

**Comment by wmn7** [comment]
感谢作者的回复.

**Comment by qianwang102** [comment]
> 
> 
> 感谢作者的回复.

你好，能否分享下作者关于怎么处理IP地址的的回复，我也遇到了相同的问题，谢谢。
