### ISSUE TITLE
HAST-IDS中PreprocessedISCX2012_5class_pkl文件

### ISSUE THREAD

**Issue by oceanzm1992** [echowei/DeepTraffic#12]
如题，您好，请问是否能提供HAST-IDS中PreprocessedISCX2012_5class_pkl文件？
给您添麻烦了，不胜感激！

**Comment by echowei** [comment]
抱歉，本打算整理所有中间代码和数据后一并补充github，但工作后时间无法保证，至今未完成。
建议：使用pkt2flow工具分flow文件后，以xml标签文件为准，按照四元组去找对应flow文件，由于分flow机制有差别，这两个结果数量有差异，无法一一对应，只能以匹配的文件做后续实验。

**Comment by Clapperclaws** [comment]
Hi! Can you please share the session and label pickles? Or the code used to convert the pcaps to pickles.

**Comment by 123Sun556** [comment]
> 如题，您好，请问是否能提供HAST-IDS中PreprocessedISCX2012_5class_pkl文件？ 给您添麻烦了，不胜感激！

您好，请问你做出来了吗

**Comment by ixiaozhuai** [comment]
> > 如题，您好，请问是否能提供HAST-IDS中PreprocessedISCX2012_5class_pkl文件？ 给您添麻烦了，不胜感激！
> 
> 您好，请问你做出来了吗

您好，请问数据集出来了嘛
