### ISSUE TITLE
关于evaluate the model模块

### ISSUE THREAD

**Issue by zokgo** [echowei/DeepTraffic#14]
作者您好，请教一下：我在win环境下跑的代码，#evaluate the model这部分10分类的能跑通，2和20分类的只训练了模型，没有跑出来acc等数据，比较疑惑原因，望解惑

**Comment by echowei** [comment]
您好，默认是10分类，需要修改tensorflow源码的一行代码，将其更改为其它分类，在文件中有说明，请参考。
