### ISSUE TITLE
处理ISCX2012数据集的时候，是否需要担心病毒问题？

### ISSUE THREAD

**Issue by KDL-in** [echowei/DeepTraffic#18]
作者你好
我想咨询这样一个问题，因为我的windows defender报毒了，先问问这种情况是否会导致计算机感染？
我google了一下没有找到对应的解答，我尝试像数据集作者，以及相关论文作者进行询问。
我不是病毒方面或网络的专家，尽管以我的计算机知识来看，合理应该是不用担心的，但是以防万一，仍然询问一下。如果作者知道的话，麻烦请告诉我一下。谢谢。

**Comment by RookieoftheYear** [comment]
您好，咨询一下您是如何处理2012数据集的么？因为我看代码最后输入的pkl文件，能简要说下处理的步骤吗

**Comment by KDL-in** [comment]
我没有使用作者的代码，所以并不知道，抱歉。很多工具包可以解析流量包，例如scapy

发件人: RookieoftheYear<mailto:notifications@github.com>
发送时间: 2020年8月29日 19:56
收件人: echowei/DeepTraffic<mailto:DeepTraffic@noreply.github.com>
抄送: KDL_in<mailto:McWarmSun@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [echowei/DeepTraffic] 处理ISCX2012数据集的时候，是否需要担心病毒问题？ (#18)


您好，咨询一下您是如何处理2012数据集的么？因为我看代码最后输入的pkl文件，能简要说下处理的步骤吗

―

**Comment by zhx-luanjishinian** [comment]
> 您好，咨询一下您是如何处理2012数据集的么？因为我看代码最后输入的pkl文件，能简要说下处理的步骤吗

您好，请问您是否下载下来2012数据集了？能否提供一下呀？

**Comment by 123Sun556** [comment]
> 您好，咨询一下您是如何处理2012数据集的么？因为我看代码最后输入的pkl文件，能简要说下处理的步骤吗

您好，您找到处理的方法了吗
