### ISSUE TITLE
关于预处理的混淆问题

### ISSUE THREAD

**Issue by WithHades** [echowei/DeepTraffic#19]
你好，
感谢您的论文以及开源的代码。
问题已经解决，可能是我把session和flow混在一起了
感谢。

**Comment by 123Sun556** [comment]
不好意思 打扰您 您有第三个hast-nad预处理后的数据集吗

**Comment by ixiaozhuai** [comment]
> 不好意思 打扰您 您有第三个hast-nad预处理后的数据集吗

您好，请问你最后获取到了数据集嘛
