### ISSUE TITLE
Few bugs in the code

### ISSUE THREAD

**Issue by Site1997** [echowei/DeepTraffic#2]
I ran the whole process, and found (and fixed) some potential bugs.

**1_Pcap2Session.ps1: foreach($f in gci 1_Pcap \*.pcap)**
This code only handle .pcap files (There are two types of files: .pcap and .pcapng). 
**Fix:** So we should first convert .pcapng to .pcap using splitcap, then run this script.

**2_ProcessSession.ps1 : $test  = $files | get-random -count (\[int\]($count/10))**
When $count is less than 10, it'll cause error, and $test is still the $test coming from the previous loop. This leads to some data wrongly classified.
**Fix:** ignore the .pcap file that has less than 10 packets.

**CNN.py : y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, w_fc2) + b_fc2)**
This would cause nan or 0 gradient if "tf.matmul(h_fc1_drop, w_fc2) + b_fc2" is all zero or nan, so when the training iteration is big enough, all weights could suddenly became 0.
**Fix:** use tf.nn.softmax_cross_entropy_with_logits instead. It handles the extreme case safely.

**Comment by echowei** [comment]
Thank you, I have fixed them according to your suggestion.

**Comment by jitendra9873** [comment]
Hello,
When I run code I am getting this error
File "encrypt_traffic_cnn_1d.py", line 134 ,
ValueError: Cannot feed value of shape(50,10) for Tensor 'Placeholder_1:0' , which has shape'(?,12)'
Can you help with what I am missing in this?

**Comment by Site1997** [comment]
It means your input data has 10 classes, but the required number of classes is 12. Have you check your dataset?

**Comment by jitendra9873** [comment]
I used these

https://github.com/echowei/DeepTraffic/tree/master/2.encrypted_traffic_classification/3.PerprocessResults

and 12class.zip file

for now

**Comment by jitendra9873** [comment]
I used the following data set to run the code.
https://github.com/echowei/DeepTraffic/tree/master/2.encrypted_traffic_classification/3.PerprocessResults
and 12class.zip file
Code should run on this dataset right?

**Comment by WANGxue708** [comment]
您好，我遇到了跟楼上同样的问题，但是我是用到的您在github上公开的预处理结果中的数据，是因为6class以及12class文件夹中的预处理结果都是10个类别的，才导致这个问题出现的吗？请问该如何修正呢？

**Comment by crrrrrrrrr** [comment]
我使用了mergecap.exe来合并两个pcap文件，但是不能使用您的PS脚本来进行预处理，提示 is not a pcap file

**Comment by jitendra9873** [comment]
> 您好，我遇到了跟楼上同样的问题，但是我是用到的您在github上公开的预处理结果中的数据，是因为6class以及12class文件夹中的预处理结果都是10个类别的，才导致这个问题出现的吗？请问该如何修正呢？

The preprocessing folder has Wrong dataset.Make your own correct dataset

**Comment by rickchen147258** [comment]
@WANGxue708 
You need to change the class number in /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py
from 10 to your class number
![image](https://user-images.githubusercontent.com/29858582/57531858-09874400-736d-11e9-8db3-557007333ef7.png)
