### ISSUE TITLE
训练集和测试集使用预处理工具处理后的测试结果很低

### ISSUE THREAD

**Issue by AsceticD** [echowei/DeepTraffic#3]
使用您给的PCAP数据和预处理工具得到的训练集和测试集与您直接提供的得到的结果完全不同，不知道是哪里出了问题，怀疑预处理或数据有问题，要不就是哪里遗漏了，或是预处理的方式不一样，我得到的训练集和测试集与您的不同，一直很困扰我，请原谅~

**Comment by echowei** [comment]
不知道您是指1.malware_traffic_classification还是2.encrypted_traffic_classification？如果是1，所有pcap数据、处理过程、选择说明都已包含，应该不存在问题。如果是2，请和数据集提供者索要完整数据集，并参照DataSet.txt列出的pcap清单处理。有问题邮件联系ww8137@ustc.mail.edu.cn。感谢关注！

**Comment by wxn0927** [comment]
> 使用您给的PCAP数据和预处理工具得到的训练集和测试集与您直接提供的得到的结果完全不同，不知道是哪里出了问题，怀疑预处理或数据有问题，要不就是哪里遗漏了，或是预处理的方式不一样，我得到的训练集和测试集与您的不同，一直很困扰我，请原谅~

您好，我在跑traffic_cnn.py文件时出现了很多错误，您当初遇到过吗？比如    DATA_DIR = sys.argv[1]
IndexError: list index out of range
方便留一个邮箱吗？想请教一下，多谢多谢
