### ISSUE TITLE
关于您提供的数据预处理结果

### ISSUE THREAD

**Issue by WANGxue708** [echowei/DeepTraffic#4]
作者您好，我读了您的文章后下载您的代码，和您提供的数据预处理结果，因为我想实验一下你提出的模型的分类准确度是多少，然后我在运行” 	encrypt_traffic_cnn_1d.py“后会提示类别不对，您提供的数据预处理结果中的6class.zip以及12class.zip中真的有6个类别以及12个类别吗？期待您的回复！祝您生活工作顺利。

**Comment by echowei** [comment]
请参考第19行# Note: if class numer is 2 or 20, please edit the variable named "num_classes" in /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py"
，如有问题，请邮件沟通，ww8137@mail.ustc.edu.cn，感谢关注！
