### ISSUE TITLE
input_data.py 文件

### ISSUE THREAD

**Issue by dirtymonkey365** [echowei/DeepTraffic#7]
作者您好，感谢开源，代码包中好像缺少input_data.py这个module，请您确认一下。期待你的回复。

**Comment by echowei** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/input_data.py

**Comment by dirtymonkey365** [comment]
非常感谢！

**Comment by qq374107200** [comment]
> 
> 
> 非常感谢！

可以发给我一下吗？这个地址无效了，我的邮箱是374107200@qq.com 非常感谢
