### ISSUE TITLE
malware这篇的一个疑惑

### ISSUE THREAD

**Issue by herunkang2018** [echowei/DeepTraffic#8]
请问malware这篇，预处理之后是每条流里每个packet的前784字节，都作为一条训练数据，还是一个流整体作为一条训练数据？如果是一个流或会话整体作为一条训练数据，打一个标签，那么是选取前三个packet还是几个？
在train_cnn.py中，好像是按照mnist的格式，即一个784字节的数据对应一个标签。所以有上述疑惑。

**Comment by wmn7** [comment]
你好, 你现在还在看这个项目, 如果可以的话可以一起讨论一下. 
我给你的邮箱emm@sparkera.net发了邮件, 但是好像邮件没有发送出去.
如果你还在做这个, 可以一起商量一下.

期待你的回复.
我的邮箱是: wangmaonan@bupt.edu.cn

**Comment by wxn0927** [comment]
> 你好, 你现在还在看这个项目, 如果可以的话可以一起讨论一下.
> 我给你的邮箱[emm@sparkera.net](mailto:emm@sparkera.net)发了邮件, 但是好像邮件没有发送出去.
> 如果你还在做这个, 可以一起商量一下.
> 
> 期待你的回复.
> 我的邮箱是: [wangmaonan@bupt.edu.cn](mailto:wangmaonan@bupt.edu.cn)

同学，你是怎么跑traffic_cnn.py的，需要加参数吗？

**Comment by echowei** [comment]
First n bytes of each flow，n=784.
