### ISSUE TITLE
运行遇到几个问题

### ISSUE THREAD

**Issue by Marin111** [echowei/DeepTraffic#9]
不知道是不是版本的问题
第一个错误
File "/DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 133, in <module>
ValueError: Cannot feed value of shape (50, 10) for Tensor u'Placeholder_1:0', which has shape '(?, 2)'

第二个错误
File "DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 107, in <module>
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

第三个问题
作者为什么要把 y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, w_fc2) + b_fc2)
注释掉呢，下面还有很多y_conv的引用。
感觉回答

**Comment by echowei** [comment]
很多邮件反馈运行成功，所以代码本身应该没问题。
可以参考https://github.com/yungshenglu/USTC-TK2016/tree/master

**Comment by qianwang102** [comment]
> 
> 
> 不知道是不是版本的问题
> 第一个错误
> File "/DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 133, in
> ValueError: Cannot feed value of shape (50, 10) for Tensor u'Placeholder_1:0', which has shape '(?, 2)'
> 
> 第二个错误
> File "DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 107, in
> ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
> 
> 第三个问题
> 作者为什么要把 y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, w_fc2) + b_fc2)
> 注释掉呢，下面还有很多y_conv的引用。
> 感觉回答

我也遇到了第一个问题，请问你解决了吗？

**Comment by GitHubLiwenqi** [comment]
> 不知道是不是版本的问题
> 第一个错误
> File "/DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 133, in
> ValueError: Cannot feed value of shape (50, 10) for Tensor u'Placeholder_1:0', which has shape '(?, 2)'
> 
> 第二个错误
> File "DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 107, in
> ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
> 
> 第三个问题
> 作者为什么要把 y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, w_fc2) + b_fc2)
> 注释掉呢，下面还有很多y_conv的引用。
> 感觉回答

您好，我也遇到了第一个问题，请问您怎么解决的呀？可以教我一下吗？谢谢！

**Comment by orchid77** [comment]
> > 不知道是不是版本的问题
> > 第一个错误
> > File "/DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 133, in
> > ValueError: Cannot feed value of shape (50, 10) for Tensor u'Placeholder_1:0', which has shape '(?, 2)'
> > 第二个错误
> > File "DeepTraffic/2.encrypted_traffic_classification/4.TrainAndTest/1d_cnn_25+3/encrypt_traffic_cnn_1d.py", line 107, in
> > ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
> > 第三个问题
> > 作者为什么要把 y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, w_fc2) + b_fc2)
> > 注释掉呢，下面还有很多y_conv的引用。
> > 感觉回答
> 
> 您好，我也遇到了第一个问题，请问您怎么解决的呀？可以教我一下吗？谢谢！

请问解决了吗
